name: Deploy to Vercel

on:
  push:
    branches:
      - main  # o 'master' si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      